name = "Tinkering"
author = "P1x3l101"
version = "2.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acfb9b7fb9a88745571c0e3b0a14c55ca5bc3ca9268c3676ea74fb8ac9390e67"

[versions]
forge = "14.23.5.2860"
lwjgl = "2.9.4-nightly-20150209"
minecraft = "1.12.2"
unsup = "1.1-pre9"
