name = "Tinkering"
author = "P1x3l101"
version = "2.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3aaa6f69dff6fd923d38e33a3fa64e74cb9c69577254f92cc83d423b26ffae4"

[versions]
forge = "14.23.5.2860"
lwjgl = "2.9.4-nightly-20150209"
minecraft = "1.12.2"
unsup = "1.1-pre9"
