name = "Tinkering"
author = "P1x3l101"
version = "2.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38cf718bde8835078de9d1d2376ff02e955aa45a581a0e41660de6a6efe70fe9"

[versions]
forge = "14.23.5.2860"
lwjgl = "2.9.4-nightly-20150209"
minecraft = "1.12.2"
unsup = "1.1-pre9"
