name = "Tinkering"
author = "P1x3l101"
version = "3.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7adc49ff4c20ea512f812b5026ffc2545ae32ea8c726cb9ae81a75af1a420c0f"

[versions]
forge = "14.23.5.2860"
lwjgl = "2.9.4-nightly-20150209"
minecraft = "1.12.2"
unsup = "1.1-beta1"
