name = "Tinkering"
author = "P1x3l101"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d36e100e55e789c690e507eded774cb65bd934d3ff39e1411789ad988aaedbaf"

[versions]
forge = "14.23.5.2860"
lwjgl = "2.9.4-nightly-20150209"
minecraft = "1.12.2"
unsup = "1.1-pre9"
