name = "Tinkering"
author = "P1x3l101"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7419b4327c48d574d8805bd6cd99554aeb282ecc1aa05030f0dc6cee4c13fec"

[versions]
forge = "14.23.5.2860"
lwjgl = "2.9.4-nightly-20150209"
minecraft = "1.12.2"
unsup = "1.1-pre9"
