name = "Tinkering"
author = "P1x3l101"
version = "2.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b3f0e4cc83f251ef82bfb9553fde2f26cf5e1b025235f4ae8504e70d93d143e"

[versions]
forge = "14.23.5.2860"
lwjgl = "2.9.4-nightly-20150209"
minecraft = "1.12.2"
unsup = "1.1-pre9"
