name = "Tinkering"
author = "P1x3l101"
version = "1.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e59e7ccc75a1ee338e1a2fb627e7d5fa2c6ea12bb05e9c9b12198a1fdd5e556"

[versions]
cleanroom = "0.3.2-alpha"
lwjgl3 = "3.3.6"
minecraft = "1.12.2"
unsup = "1.1-pre9"
