name = "Tinkering"
author = "P1x3l101"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8ef2c25401beea5ee75cbeabc5ff3587b1a9330dc53eecce6ba4b5d0b3d690a"

[versions]
forge = "14.23.5.2860"
lwjgl = "2.9.4-nightly-20150209"
minecraft = "1.12.2"
unsup = "1.1-pre9"
