name = "Tinkering"
author = "P1x3l101"
version = "2.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6c863dbe37da173744ee67ab1dbadfefedf20ff6266f1965011c8219c638b02"

[versions]
forge = "14.23.5.2860"
lwjgl = "2.9.4-nightly-20150209"
minecraft = "1.12.2"
unsup = "1.1-beta1"
