name = "Tinkering"
author = "P1x3l101"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf85c8fda3975d3b2ebcf7ca380665f60a949c31c8befd27645b7a37ae1d1533"

[versions]
forge = "14.23.5.2860"
lwjgl = "2.9.4-nightly-20150209"
minecraft = "1.12.2"
unsup = "1.1-pre9"
