name = "Tinkering"
author = "P1x3l101"
version = "1.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abe706f167af8c2faa9f34d14dbc43bb1eb19c9b327911ebfa6e972a59225165"

[versions]
forge = "14.23.5.2860"
lwjgl = "2.9.4-nightly-20150209"
minecraft = "1.12.2"
unsup = "1.1-pre9"
