name = "Tinkering"
author = "P1x3l101"
version = "2.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ffaafd844d6cc0792ff857ace49b178021943af7e7bf4c0a9707dcbdd1446b9"

[versions]
forge = "14.23.5.2860"
lwjgl = "2.9.4-nightly-20150209"
minecraft = "1.12.2"
unsup = "1.1-beta1"
