name = "Tinkering"
author = "P1x3l101"
version = "1.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d202d07f143bff6b808ce3cfeb63911ee00861c4cd847df22b24f38ff8934d5"

[versions]
cleanroom = "0.3.2-alpha"
lwjgl3 = "3.3.6"
minecraft = "1.12.2"
unsup = "1.1-pre9"
