name = "Tinkering"
author = "P1x3l101"
version = "2.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20d964e62014b157ddad0b7437158a7e8bd3c9e1ec5e0abdf3280fdc91b5a575"

[versions]
forge = "14.23.5.2860"
lwjgl = "2.9.4-nightly-20150209"
minecraft = "1.12.2"
unsup = "1.1-pre9"
