name = "Tinkering"
author = "P1x3l101"
version = "3.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5eb74b787f61f8a9ac55fce5a0bbd48a143da409ba5d6b8ccf698134b8ac6db4"

[versions]
forge = "14.23.5.2860"
lwjgl = "2.9.4-nightly-20150209"
minecraft = "1.12.2"
unsup = "1.1-beta1"
