name: Build
on:
  workflow_dispatch:
  push:
    paths:
      - pack.toml
      - unsup.sig
      - .packwizignore
jobs:
  validate:
    name: Validate signatures
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Check unsup-packwiz signature against file and pubkey
        run: openssl pkeyutl -verify -rawin -pubin -inkey autosign/key.pub.pem -sigfile unsup.sig -in pack.toml
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install packwiz
      uses: ./.github/actions/install-packwiz
    - name: Export for curseforge
      run: packwiz curseforge export --output curseforge.zip
    - name: Create a prismlauncher instance
      uses: ./.github/actions/generate-prism-pack
      with:
        outputFile: prismlauncher.zip
    - name: Upload assets
      uses: actions/upload-artifact@v4
      with:
        name: Bundles
        path: |
          curseforge.zip
          prismlauncher.zip